#!/bin/sh

export GDK_SCALE=2
export GDK_DPI_SCALE=0.5

export QT_AUTO_SCREEN_SET_FACTOR=0
export QT_AUTO_SCREEN_SCALE_FACTOR=0
export QT_SCREEN_SCALE_FACTORS=2
export QT_QPA_PLATFORMTHEME=qt5ct
export QT_SCALE_FACTOR=2
export QT_FONT_DPI=130
export GDK_DPI_SCALE=0.5